# Python support can be specified down to the minor or micro version
# (e.g. 3.6 or 3.6.3).
# OS Support also exists for jessie & stretch (slim and full).
# See https://hub.docker.com/r/library/python/ for all supported Python
# tags from Docker Hub.
FROM python:alpine
ENV PYTHONUNBUFFERED 1

# If you prefer miniconda:
#FROM continuumio/miniconda3

LABEL Name=django Version=0.0.1
EXPOSE 8000

WORKDIR /app
ADD . /app

# Psycopg2
RUN apk add --no-cache --virtual .build-deps \
    ca-certificates gcc postgresql-dev linux-headers musl-dev \
    libffi-dev jpeg-dev zlib-dev 

# Upgrading PIP
RUN python -m pip install --upgrade pip

# Using pip:
RUN pip install -r requirements.txt
CMD ["python3", "-m", "messenger"]

# Using pipenv:
#RUN python3 -m pip install pipenv
#RUN pipenv install --ignore-pipfile
#CMD ["pipenv", "run", "python3", "-m", "messenger"]

# Using miniconda (make sure to replace 'myenv' w/ your environment name):
#RUN conda env create -f environment.yml
#CMD /bin/bash -c "source activate myenv && python3 -m messenger"
