version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis
  django:
    image: django
    build: .
    command: sh entry.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  
