version: '3.7'

services:
  db:
    image: postgres
  redis:
    image: redis
  messenger:
    image: messenger
    build: .
    command: sh entry.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  
